# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-FC2-SpamAPI
version:      0.01
version_from: lib/WebService/FC2/SpamAPI.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Encode:                        0
    Test::More:                    0
    URI:                           0
    URI::Fetch:                    0
    URI::QueryParam:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
